In [362]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [363]:
data = pd.read_csv('churn_prediction.csv')

In [364]:
data.head()

customer_id  vintage  age gender  dependents     occupation    city  \
0            1     2101   66   Male         0.0  self_employed   187.0   
1            2     2348   35   Male         0.0  self_employed     NaN   
2            4     2194   31   Male         0.0       salaried   146.0   
3            5     2329   90    NaN         NaN  self_employed  1020.0   
4            6     1579   42   Male         2.0  self_employed  1494.0   

   customer_nw_category  branch_code  current_balance  ...  \
0                     2          755          1458.71  ...   
1                     2         3214          5390.37  ...   
2                     2           41          3913.16  ...   
3                     2          582          2291.91  ...   
4                     3          388           927.72  ...   

   average_monthly_balance_prevQ  average_monthly_balance_prevQ2  \
0                        1458.71                         1449.07   
1                        7799.26                        12419.41   
2                        4910.17                         2815.94   
3                        2084.54                         1006.54   
4                        1643.31                         1871.12   

   current_month_credit  previous_month_credit  current_month_debit  \
0                  0.20                   0.20                 0.20   
1                  0.56                   0.56              5486.27   
2                  0.61                   0.61              6046.73   
3                  0.47                   0.47                 0.47   
4                  0.33                 714.61               588.62   

   previous_month_debit  current_month_balance  previous_month_balance  churn  \
0                  0.20                1458.71                 1458.71      0   
1                100.56                6496.78                 8787.61      0   
2                259.23                5006.28                 5070.14      0   
3               2143.33                2291.91                 1669.79      1   
4               1538.06                1157.15                 1677.16      1   

   last_transaction  
0        2019-05-21  
1        2019-11-01  
2               NaT  
3        2019-08-06  
4        2019-11-03  

[5 rows x 21 columns]

In [365]:
data.dtypes

customer_id                         int64
vintage                             int64
age                                 int64
gender                             object
dependents                        float64
occupation                         object
city                              float64
customer_nw_category                int64
branch_code                         int64
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
churn                               int64
last_transaction                   object
dtype: object

In [366]:
data = data.drop(columns= ['customer_id'])

In [367]:
data['gender'].unique()

array(['Male', nan, 'Female'], dtype=object)

In [368]:
data = data.rename(columns={ 'gender': 'is_male' })

In [369]:
def encode_gender(val):
    if val == 'Male':
        return 1
    elif val == 'Female':
        return 0
    else :
        return 1
    

In [370]:

data['is_male']= data['is_male'].map(encode_gender)

In [371]:
data['is_male'].unique()

array([1, 0], dtype=int64)

In [372]:
data.isnull().sum()


vintage                              0
age                                  0
is_male                              0
dependents                        2463
occupation                          80
city                               803
customer_nw_category                 0
branch_code                          0
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 0
current_month_balance                0
previous_month_balance               0
churn                                0
last_transaction                     0
dtype: int64

In [373]:
data['city'].unique()

array([ 187.,   nan,  146., ...,  556., 1167.,  723.])

In [374]:
data['occupation'].unique()

array(['self_employed', 'salaried', 'retired', 'student', nan, 'company'],
      dtype=object)

In [375]:
data['occupation'].mode()

0    self_employed
Name: occupation, dtype: object

In [376]:
def encode_occupation(val):
    if val == 'student' :
        return 0
    elif val == 'self_employed' :
        return 1
    elif val == 'salaried' :
        return 2
    elif val == 'company' :
        return 3
    elif val == 'retired' :
        return 4
    else :
        return 1

In [377]:
data['occupation']= data['occupation'].map(encode_occupation)

In [378]:
data['occupation'].unique()

array([1, 2, 4, 0, 3], dtype=int64)

In [379]:
data = data.drop(columns = ['city'])

In [380]:
data['dependents'].mode()

0    0.0
Name: dependents, dtype: float64

In [381]:
data['dependents'].mean()

0.34723561865812724

In [382]:
data['dependents'].median()

0.0

In [383]:
def impute_dependents(val):
    if type (val)!= type(6.2):
        return 0 


In [384]:
data['dependents'] = data['dependents'].fillna(0)

In [385]:
data['dependents'].unique()

array([ 0.,  2.,  3.,  1.,  7.,  4.,  6.,  5.,  9., 52., 36., 50.,  8.,
       25., 32.])

In [386]:
data.dtypes

vintage                             int64
age                                 int64
is_male                             int64
dependents                        float64
occupation                          int64
customer_nw_category                int64
branch_code                         int64
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
churn                               int64
last_transaction                   object
dtype: object

In [387]:
data.isnull().sum()

vintage                           0
age                               0
is_male                           0
dependents                        0
occupation                        0
customer_nw_category              0
branch_code                       0
current_balance                   0
previous_month_end_balance        0
average_monthly_balance_prevQ     0
average_monthly_balance_prevQ2    0
current_month_credit              0
previous_month_credit             0
current_month_debit               0
previous_month_debit              0
current_month_balance             0
previous_month_balance            0
churn                             0
last_transaction                  0
dtype: int64

In [388]:
data['last_transaction'].unique()

array(['2019-05-21', '2019-11-01', 'NaT', '2019-08-06', '2019-11-03',
       '2019-09-24', '2019-07-12', '2019-12-12', '2019-12-31',
       '2019-12-26', '2019-12-11', '2019-11-14', '2019-03-03',
       '2019-11-09', '2019-12-28', '2019-10-23', '2019-11-30',
       '2019-12-08', '2019-12-18', '2019-12-27', '2019-12-22',
       '2019-12-04', '2019-11-25', '2019-10-15', '2019-08-28',
       '2019-12-21', '2019-09-25', '2019-10-31', '2019-12-05',
       '2019-09-22', '2019-12-24', '2019-12-20', '2019-07-24',
       '2019-12-17', '2019-09-27', '2019-12-14', '2019-09-06',
       '2019-10-16', '2019-12-13', '2019-12-03', '2019-12-06',
       '2019-07-11', '2019-11-15', '2019-12-19', '2019-12-25',
       '2019-08-15', '2019-08-27', '2019-11-12', '2019-05-15',
       '2019-11-16', '2019-10-17', '2019-05-26', '2019-10-22',
       '2019-12-01', '2019-07-04', '2019-11-22', '2019-04-16',
       '2019-06-26', '2019-02-06', '2019-10-11', '2019-03-09',
       '2019-10-29', '2019-07-10', '2019-09-26',

In [389]:
import time 

In [390]:
data['last_transaction'] = pd.to_datetime(data['last_transaction'])

In [391]:
data.dtypes

vintage                                    int64
age                                        int64
is_male                                    int64
dependents                               float64
occupation                                 int64
customer_nw_category                       int64
branch_code                                int64
current_balance                          float64
previous_month_end_balance               float64
average_monthly_balance_prevQ            float64
average_monthly_balance_prevQ2           float64
current_month_credit                     float64
previous_month_credit                    float64
current_month_debit                      float64
previous_month_debit                     float64
current_month_balance                    float64
previous_month_balance                   float64
churn                                      int64
last_transaction                  datetime64[ns]
dtype: object

In [393]:
data.to_csv('placed_data.csv', index = False)